name: coffee_maker
description: The coffee maker example project to demonstrate the usage of wolt_modal_sheet library
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  provider: ^6.0.5
  wolt_responsive_layout_grid: ^0.0.3
  wolt_modal_sheet:
    path: ..
  demo_ui_components:
    path: ../demo_ui_components

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.18.2

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/fonts/
