name: wolt_di
description: This internal package provides a dependency injection mechanism 
  for demo apps.

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.1
  # Flutter test tools
  flutter_test:
    sdk: flutter
  # Test lib.
  test: ^1.18.2
